import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { ItemValidation, ChecklistConfig, Entity } from '@/lib/schemas';

/**
 * Interfaz para los reportes de auditoría de validación de entidad.
 */
export interface AuditReportData {
    entity: Entity;
    config: ChecklistConfig;
    items: ItemValidation[];
    userName: string;
    durationMs: number;
    timestamp: Date;
    correlationId: string;
}

/**
 * Interfaz para registros de auditoría de sistema (logs).
 */
export interface AuditLog {
    _id: string;
    level: string;
    source: string;
    action: string;
    message: string;
    userEmail?: string;
    performedBy?: string;
    timestamp: string | Date;
    correlationId?: string;
}

/**
 * Genera un PDF de auditoría para la validación de un pedido (Vista Técnica).
 */
export async function generateValidationAuditPDF(data: AuditReportData, locale: string = 'es'): Promise<Blob> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let y = 20;

    const t = locale === 'es' ? {
        title: "INFORME DE TRAZABILIDAD TÉCNICA",
        subtitle: `Validación de Entidad: ${data.entity.identifier}`,
        summaryTitle: "Resumen de la Sesión",
        validator: "Técnico Responsable",
        date: "Fecha/Hora",
        duration: "Tiempo de Revisión",
        config: "Protocolo Aplicado",
        resultsTitle: "Puntos de Control Verificados",
        footnote: "Documento generado por ABD RAG Intelligence Platform"
    } : {
        title: "TECHNICAL AUDIT TRAIL REPORT",
        subtitle: `Entity Validation: ${data.entity.identifier}`,
        summaryTitle: "Session Summary",
        validator: "Responsible Technician",
        date: "Date/Time",
        duration: "Review Time",
        config: "Applied Protocol",
        resultsTitle: "Verified Control Points",
        footnote: "Document generated by ABD RAG Intelligence Platform"
    };

    // Header
    pdf.setFillColor(15, 23, 42); // Slate-900
    pdf.rect(0, 0, pageWidth, 40, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text(t.title, 15, 18);

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(t.subtitle, 15, 28);
    pdf.text(`ID Seguimiento: ${data.correlationId}`, 15, 34);

    y = 55;

    // Summary Section
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(t.summaryTitle, 15, y);
    y += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${t.validator}: ${data.userName}`, 15, y);
    pdf.text(`${t.date}: ${data.timestamp.toLocaleString(locale === 'es' ? 'es-ES' : 'en-US')}`, 100, y);
    y += 6;
    pdf.text(`${t.duration}: ${Math.floor(data.durationMs / 1000)}s`, 15, y);
    pdf.text(`${t.config}: ${data.config.name}`, 100, y);
    y += 15;

    // Results
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(t.resultsTitle, 15, y);
    y += 10;

    data.items.forEach((item, index) => {
        if (y > pageHeight - 40) {
            pdf.addPage();
            y = 20;
        }

        pdf.setFillColor(248, 250, 252);
        pdf.rect(15, y - 5, pageWidth - 30, 22, 'F');

        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(10);
        pdf.setTextColor(15, 23, 42);
        pdf.text(`${index + 1}. [${item.status}] ${item.itemId}`, 18, y);

        y += 6;
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(9);
        pdf.setTextColor(71, 85, 105);
        const notes = item.notes || (locale === 'es' ? 'Sin observaciones.' : 'No observations.');
        const splitText = pdf.splitTextToSize(notes, pageWidth - 40);
        pdf.text(splitText, 18, y);

        y += (splitText.length * 4) + 8;
    });

    // Footnote
    pdf.setFontSize(8);
    pdf.setTextColor(148, 163, 184);
    pdf.text(`${t.footnote} | ID: ${data.correlationId}`, pageWidth / 2, pageHeight - 10, { align: 'center' });

    return pdf.output('blob');
}

/**
 * Generates a PDF document for generic system logs.
 */
export async function generateGenericAuditPDF(logs: AuditLog[], filters: any, locale: string = 'es') {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    const t = locale === 'es' ? {
        title: "REGISTRO DE OPERACIONES SEGURAS",
        period: "Periodo",
        table: { date: "Fecha", action: "Acción", user: "Usuario", module: "Módulo" }
    } : {
        title: "SECURE OPERATIONS LOG",
        period: "Period",
        table: { date: "Date", action: "Action", user: "User", module: "Module" }
    };

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(t.title, 14, 15);
    doc.setFontSize(9);
    doc.text(`${t.period}: ${filters.dateRange?.from || 'Start'} - ${filters.dateRange?.to || 'End'}`, 14, 22);

    (doc as any).autoTable({
        startY: 40,
        head: [[t.table.date, t.table.action, t.table.user, t.table.module]],
        body: logs.map(log => [
            new Date(log.timestamp).toLocaleString(),
            log.action,
            log.performedBy || log.userEmail || 'System',
            log.source
        ]),
        headStyles: { fillColor: [15, 23, 42] }
    });

    doc.save(`Audit_${new Date().getTime()}.pdf`);
}
