
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { ItemValidation, ChecklistConfig, Entity } from '@/lib/schemas';
import { PdfLayout } from './pdf/PdfLayout';
import { PdfTheme } from './pdf/PdfTheme';

/**
 * Interfaz para los reportes de auditoría de validación de entidad.
 */
export interface AuditReportData {
    entity: Entity;
    config: ChecklistConfig;
    items: ItemValidation[];
    userName: string;
    durationMs: number;
    timestamp: Date;
    correlationId: string;
    tenantId: string;
}

/**
 * Interfaz para registros de auditoría de sistema (logs).
 */
export interface AuditLog {
    _id: string;
    level: string;
    source: string;
    action: string;
    message: string;
    userEmail?: string;
    performedBy?: string;
    timestamp: string | Date;
    correlationId?: string;
}

/**
 * Genera un PDF de auditoría para la validación de un pedido (Vista Técnica).
 * Phase 8.1: Unified Layout & Tracing.
 */
export async function generateValidationAuditPDF(data: AuditReportData, locale: string = 'es'): Promise<Blob> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const theme = PdfTheme.getTheme(locale);

    // Metadata
    PdfLayout.attachDocumentMetadata(pdf, {
        tenantId: data.tenantId,
        correlationId: data.correlationId,
        generatedBy: data.userName
    });

    const t = locale === 'es' ? {
        title: "INFORME DE TRAZABILIDAD TÉCNICA",
        subtitle: `Validación de Entidad: ${data.entity.identifier}`,
        summaryTitle: "Resumen de la Sesión",
        validator: "Técnico Responsable",
        date: "Fecha/Hora",
        duration: "Tiempo de Revisión",
        config: "Protocolo Aplicado",
        resultsTitle: "Puntos de Control Verificados",
        footnote: "Documento generado por ABD RAG Intelligence Platform"
    } : {
        title: "TECHNICAL AUDIT TRAIL REPORT",
        subtitle: `Entity Validation: ${data.entity.identifier}`,
        summaryTitle: "Session Summary",
        validator: "Responsible Technician",
        date: "Date/Time",
        duration: "Review Time",
        config: "Applied Protocol",
        resultsTitle: "Verified Control Points",
        footnote: "Document generated by ABD RAG Intelligence Platform"
    };

    // Header unificado
    let y = PdfLayout.drawStandardHeader(pdf, {
        title: t.title,
        subtitle: t.subtitle,
        correlationId: data.correlationId,
        locale
    });

    // Summary Section
    y = PdfLayout.drawSectionTitle(pdf, t.summaryTitle, y, locale);

    pdf.setFontSize(PdfTheme.FONTS.BODY);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(theme.colors.secondary);
    pdf.text(`${t.validator}: ${data.userName}`, PdfTheme.MARGINS.LEFT, y);
    pdf.text(`${t.date}: ${PdfTheme.formatDate(data.timestamp, locale)}`, 110, y);
    y += 6;
    pdf.text(`${t.duration}: ${Math.floor(data.durationMs / 1000)}s`, PdfTheme.MARGINS.LEFT, y);
    pdf.text(`${t.config}: ${data.config.name}`, 110, y);
    y += 15;

    // Results
    y = PdfLayout.drawSectionTitle(pdf, t.resultsTitle, y, locale);

    data.items.forEach((item, index) => {
        // Ensure space or jump page
        y = PdfLayout.ensurePageSpace(pdf, y, 25);

        pdf.setFillColor(theme.colors.background);
        pdf.rect(PdfTheme.MARGINS.LEFT, y - 5, pageWidth - (PdfTheme.MARGINS.LEFT + PdfTheme.MARGINS.RIGHT), 22, 'F');

        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(PdfTheme.FONTS.BODY);
        pdf.setTextColor(theme.colors.secondary);
        pdf.text(`${index + 1}. [${item.status}] ${item.itemId}`, PdfTheme.MARGINS.LEFT + 3, y);

        y += 6;
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(PdfTheme.FONTS.SMALL);
        pdf.setTextColor(theme.colors.muted);
        const notes = item.comments || (locale === 'es' ? 'Sin observaciones.' : 'No observations.');
        const splitText = pdf.splitTextToSize(notes, pageWidth - (PdfTheme.MARGINS.LEFT + PdfTheme.MARGINS.RIGHT + 10));
        pdf.text(splitText, PdfTheme.MARGINS.LEFT + 3, y);

        y += (splitText.length * 4) + 8;
    });

    // Footnote unificado
    PdfLayout.drawStandardFooter(pdf, data.correlationId, locale);

    return pdf.output('blob');
}

/**
 * Generates a PDF document for generic system logs.
 */
export async function generateGenericAuditPDF(logs: AuditLog[], filters: any, locale: string = 'es') {
    const doc = new jsPDF();
    const theme = PdfTheme.getTheme(locale);

    const t = locale === 'es' ? {
        title: "REGISTRO DE OPERACIONES SEGURAS",
        period: "Periodo",
        table: { date: "Fecha", action: "Acción", user: "Usuario", module: "Módulo" }
    } : {
        title: "SECURE OPERATIONS LOG",
        period: "Period",
        table: { date: "Date", action: "Action", user: "User", module: "Module" }
    };

    // Standard Header
    PdfLayout.drawStandardHeader(doc, {
        title: t.title,
        subtitle: `${t.period}: ${filters.dateRange?.from || 'Start'} - ${filters.dateRange?.to || 'End'}`,
        locale
    });

    (doc as any).autoTable({
        startY: 50,
        head: [[t.table.date, t.table.action, t.table.user, t.table.module]],
        body: logs.map(log => [
            new Date(log.timestamp).toLocaleString(),
            log.action,
            log.performedBy || log.userEmail || 'System',
            log.source
        ]),
        headStyles: { fillColor: theme.colors.secondary as any }
    });

    // Standard Footer
    PdfLayout.drawStandardFooter(doc, undefined, locale);

    doc.save(`Audit_${new Date().getTime()}.pdf`);
}
