import { NextRequest, NextResponse } from 'next/server';
import { SovereignOntologyService } from '@/lib/self-evolving-ontology';
import { requireSuperAdmin } from '@/lib/auth';
import { logEvento } from '@/lib/logger';
import crypto from 'crypto';

/**
 * 🔬 API: Ontology Evolution Review (Vision 2027+)
 * Allows SuperAdmins to see the "drift" and refinement proposals generated by the Sovereign Engine.
 */
export async function GET(req: NextRequest) {
    const correlationId = crypto.randomUUID();

    try {
        await requireSuperAdmin();

        const tenantId = req.nextUrl.searchParams.get('tenantId') || 'SYSTEM';
        const proposals = await SovereignOntologyService.generateProposals(tenantId, correlationId);
        const drift = await SovereignOntologyService.analyzeFeedbackDrift(tenantId);

        return NextResponse.json({
            success: true,
            tenantId,
            evolution: {
                totalDriftPoints: drift.length,
                pendingProposals: proposals.length,
                proposals,
                driftSummary: drift.map(d => ({
                    target: d._id.category || 'General',
                    from: d._id.original,
                    to: d._id.corrected,
                    frequency: d.count
                }))
            },
            correlationId
        });

    } catch (error: any) {
        await logEvento({
            level: 'ERROR',
            source: 'API_ONTOLOGY_EVOLUTION',
            action: 'GET_FAILED',
            message: `Error al obtener evolución de ontología: ${error.message}`,
            correlationId,
            details: { stack: error.stack }
        });

        return NextResponse.json({
            success: false,
            error: error.message
        }, { status: 500 });
    }
}
