import { jsPDF } from 'jspdf';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

/**
 * 📄 PDFExportService
 * Handles the generation of certified PDF reports for SGSI.
 * Era 15: Advanced Compliance.
 */
export class PDFExportService {
    /**
     * Generates a certified PDF from Markdown content.
     */
    static async generateCertifiedPDF(
        markdownContent: string, 
        outputPath: string,
        metadata: { title: string; period: string; emitter: string }
    ): Promise<string> {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        // 1. Header (Branding)
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.setTextColor(15, 23, 42); // slate-900
        doc.text('ABD ELEVATORS', 20, 25);
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139); // slate-500
        doc.text('SGSI TECHNICAL EVIDENCE | ISO 27001 COMPLIANCE', 20, 32);

        // Divider
        doc.setDrawColor(226, 232, 240); // slate-200
        doc.line(20, 38, pageWidth - 20, 38);

        // 2. Title & Metadata
        doc.setFontSize(18);
        doc.setTextColor(30, 41, 59); // slate-800
        doc.setFont('helvetica', 'bold');
        doc.text(metadata.title.toUpperCase(), 20, 55);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Periodo: ${metadata.period}`, 20, 65);
        doc.text(`Emisor: ${metadata.emitter}`, 20, 70);
        doc.text(`Fecha Certificación: ${new Date().toLocaleDateString('es-ES')}`, 20, 75);

        // 3. Content Parsing (Simplified Markdown to PDF)
        // We split by sections and tables. This is a basic implementation.
        const lines = markdownContent.split('\n');
        let currentY = 90;

        doc.setFontSize(11);
        doc.setTextColor(51, 65, 85); // slate-700

        for (const line of lines) {
            if (line.startsWith('# ')) continue; // Already handled by title
            if (line.startsWith('## ')) {
                currentY += 10;
                doc.setFont('helvetica', 'bold');
                doc.text(line.replace('## ', ''), 20, currentY);
                doc.setFont('helvetica', 'normal');
                currentY += 8;
            } else if (line.startsWith('### ')) {
                currentY += 8;
                doc.setFont('helvetica', 'bold');
                doc.text(line.replace('### ', ''), 20, currentY);
                doc.setFont('helvetica', 'normal');
                currentY += 6;
            } else if (line.includes('|')) {
                // Table like line
                if (line.includes('---')) continue;
                doc.setFont('courier', 'normal');
                doc.setFontSize(10);
                doc.text(line, 20, currentY);
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(11);
                currentY += 6;
            } else if (line.trim() === '') {
                currentY += 3;
            } else {
                // Regular text
                const splitText = doc.splitTextToSize(line, pageWidth - 40);
                doc.text(splitText, 20, currentY);
                currentY += (splitText.length * 6);
            }

            // Page break check
            if (currentY > pageHeight - 40) {
                doc.addPage();
                currentY = 25;
            }
        }

        // 4. Integrity Footer (SHA-256)
        const pdfContent = doc.output();
        const hash = crypto.createHash('sha256').update(pdfContent).digest('hex');

        doc.setFont('courier', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // slate-400
        
        // Add hash on all pages (simplified: last page for now)
        doc.text('--------------------------------------------------------------------------------', 20, pageHeight - 25);
        doc.text(`INTEGRITY HASH (SHA-256): ${hash}`, 20, pageHeight - 20);
        doc.text('ABD SECURITY SEAL - GENERATED BY SGSI ORCHESTRATOR', 20, pageHeight - 15);

        // Save file
        const buffer = Buffer.from(doc.output('arraybuffer'));
        fs.writeFileSync(outputPath, buffer);

        return hash;
    }
}
