import { jsPDF } from 'jspdf';
import { logEvento } from '@/lib/logger';

interface LLMReportPDFData {
    identifier: string;
    client: string;
    content: string; // Markdown
    tenantId: string;
    date: Date;
    technician: string;
}

/**
 * Generates a PDF on the server from the content of an LLM report.
 * Designed to run in Node.js environments (Vercel).
 */
export async function generateServerPDF(data: LLMReportPDFData): Promise<Buffer> {
    const start = Date.now();

    // In Node.js, jspdf doesn't have easy access to local fonts or DOM,
    // but we can use standard fonts (Helvetica, Times, Courier).
    const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
        putOnlyUsedFonts: true
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = 20;

    // Header
    doc.setFillColor(13, 148, 136); // Teal-600
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('ABD RAG PLATFORM', margin, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('PROFESSIONAL TECHNICAL REPORT (IA ASSISTED)', margin, 25);
    doc.text(`Tenant ID: ${data.tenantId} | Entity: ${data.identifier}`, margin, 32);

    y = 55;

    // Info Section
    doc.setTextColor(51, 65, 85); // Slate-700
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Report Details', margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Client: ${data.client}`, margin, y);
    y += 5;
    doc.text(`Date: ${data.date.toLocaleString('en-US')}`, margin, y);
    y += 5;
    doc.text(`Responsible Technician: ${data.technician}`, margin, y);
    y += 15;

    // Content (Simplified Markdown)
    // jspdf doesn't natively render markdown, so we do basic parsing
    // for bold and page breaks.
    doc.setTextColor(0, 0, 0);
    const lines = data.content.split('\n');

    for (const line of lines) {
        // Preventive page break
        if (y > pageHeight - 20) {
            doc.addPage();
            y = 20;
        }

        if (line.startsWith('# ')) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(16);
            doc.text(line.substring(2), margin, y);
            y += 10;
        } else if (line.startsWith('## ')) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            doc.text(line.substring(3), margin, y);
            y += 8;
        } else if (line.startsWith('### ')) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(12);
            doc.text(line.substring(4), margin, y);
            y += 6;
        } else if (line.trim() === '') {
            y += 4;
        } else {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);

            // Basic bold replacement **text** -> remove asterisks to avoid visual glitches
            const cleanLine = line.replace(/\*\*/g, '');

            const wrappedText = doc.splitTextToSize(cleanLine, contentWidth);

            // Page break check
            if (y + (wrappedText.length * 5) > pageHeight - 20) {
                doc.addPage();
                y = 20;
            }

            doc.text(wrappedText, margin, y);
            y += (wrappedText.length * 5) + 2;
        }
    }

    // Footer
    const totalPages = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.text(
            `Page ${i} of ${totalPages} | Report automatically generated by RAG Engine v2.0`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    const duration = Date.now() - start;
    await logEvento({
        level: 'DEBUG',
        source: 'SERVER_PDF_UTILS',
        action: 'GENERATE_PDF',
        message: `PDF generated on server for ${data.identifier}`,
        correlationId: 'pdf-gen-' + Date.now(),
        details: { durationMs: duration, pages: totalPages }
    });

    const pdfOutput = doc.output('arraybuffer');
    return Buffer.from(pdfOutput);
}
