import { z } from 'zod';
import { Annotation, StateGraph, START, END } from "@langchain/langgraph";
import { RagResult } from "@abd/rag-engine";
import { hybridSearch, performTechnicalSearch } from "@abd/rag-engine/server";
import { PromptRunner } from "@/lib/llm-core/PromptRunner";
import { logEvento } from "@/lib/logger";
import { withCorrelation } from "@/lib/logger/with-correlation";
import { MongoDBSaver } from "@/lib/agent-persistence";
import { FederatedKnowledgeService } from "@/services/core/FederatedKnowledgeService";
import { AIModelFindingSchema, AIRiskFindingSchema } from "@/types/ai";

/**
 * Represents the agent state during the analysis process.
 * Following Phase 21 of the Roadmap.
 */
export const AgentState = Annotation.Root({
    /**
     * Conversation message history / trace
     */
    messages: Annotation<{ role: string, content: string }[]>({
        reducer: (x, y) => x.concat(y),
    }),

    /**
     * Context chunks retrieved from RAG
     */
    context_chunks: Annotation<RagResult[]>({
        reducer: (x, y) => x.concat(y),
        default: () => [],
    }),

    /**
     * Confidence score of the current analysis (0-1)
     */
    confidence_score: Annotation<number>({
        reducer: (x, y) => y ?? x,
        default: () => 0,
    }),

    /**
     * References to other languages if multilingual content detected
     */
    multilingual_refs: Annotation<string[]>({
        reducer: (x, y) => Array.from(new Set([...x, ...y])),
        default: () => [],
    }),

    /**
     * Specific findings (models, risks, etc)
     */
    findings: Annotation<Record<string, unknown>[]>({
        reducer: (x, y) => x.concat(y),
        default: () => [],
    }),

    /**
     * ID of the order being analyzed
     */
    orderId: Annotation<string>({
        reducer: (x, y) => y ?? x,
    }),

    /**
     * Tenant ID for isolation
     */
    tenantId: Annotation<string>({
        reducer: (x, y) => y ?? x,
    }),

    /**
     * Additional search queries generated by the critic
     */
    search_queries: Annotation<string[]>({
        reducer: (x, y) => x.concat(y),
        default: () => [],
    }),

    /**
     * Correlation ID for logging
     */
    correlationId: Annotation<string>({
        reducer: (x, y) => y ?? x,
    }),

    /**
     * Dynamic context
     */
    industry: Annotation<string>({
        reducer: (x, y) => y ?? x,
        default: () => 'GENERIC',
    }),
    environment: Annotation<string>({
        reducer: (x, y) => y ?? x,
        default: () => 'PRODUCTION',
    }),

    /**
     * Federated insights (Vision 2027)
     */
    federated_insights: Annotation<Record<string, unknown>[]>({
        reducer: (x, y) => x.concat(y),
        default: () => [],
    }),
});

export type AgentStateType = typeof AgentState.State;

/**
 * NODE: Model Extraction
 * Uses Gemini Flash to identify what is being requested.
 */
async function extractionNode(state: AgentStateType) {
    const { tenantId, correlationId, industry } = state;
    const lastMessage = state.messages[state.messages.length - 1];
    const text = typeof lastMessage === 'string' ? lastMessage : lastMessage.content;

    // Rule #12: Prompt Governance - Use PromptRunner.runJson
    const models = await PromptRunner.runJson({
        key: 'AGENT_MODEL_EXTRACTION',
        variables: { text, industry },
        schema: z.array(AIModelFindingSchema),
        tenantId: tenantId!,
        correlationId: correlationId!,
        temperature: 0.1,
        task: 'AGENT_EXTRACTION'
    });

    return {
        findings: models.map((m) => ({ ...m, source: 'extraction' })),
        messages: [{ role: 'assistant', content: `Detected components: ${models.map((m) => m.model).join(', ')}` }]
    };
}

/**
 * NODE: Technical Search (RAG)
 * Retrieves relevant context from the technical corpus based on detected models.
 */
async function retrievalNode(state: AgentStateType) {
    const { findings, tenantId, correlationId, search_queries } = state;

    // Use specific queries from critic if available, otherwise use model-based queries
    const queries = search_queries.length > 0
        ? [search_queries[search_queries.length - 1]]
        : findings.filter(f => f.source === 'extraction').map(m => `Technical specifications and regulations for ${m.type} model ${m.model}`);

    let allChunks: RagResult[] = [];

    for (const query of queries) {
        const chunks = await performTechnicalSearch(
            query as string,
            tenantId!,
            correlationId!,
            search_queries.length > 0 ? 5 : 3, // More depth for correction search
            state.industry,
            state.environment
        );
        allChunks = [...allChunks, ...chunks];
    }

    return {
        context_chunks: allChunks,
        messages: [{ role: 'assistant', content: `Retriever: Recovered ${allChunks.length} relevant technical fragments for: ${queries.join(', ')}` }]
    };
}



/**
 * NODE: Risk Validation
 * Analyzes the cross-reference between the order and RAG to detect incompatibilities.
 */
async function riskAnalysisNode(state: AgentStateType) {
    const { context_chunks, findings, tenantId, correlationId, federated_insights, industry } = state;

    const context = context_chunks.map(c => c.text).join('\n---\n');
    const globalPatterns = federated_insights?.map(p => `- PROBLEM: ${p.problemVector}\n  SOLUTION: ${p.solutionVector}`).join('\n') || 'No global patterns found.';
    const models = findings.filter(f => f.source === 'extraction').map(f => f.model).join(', ');

    try {
        // Rule #12: Prompt Governance - Use PromptRunner.runJson
        const parsed = await PromptRunner.runJson({
            key: 'AGENT_RISK_ANALYSIS',
            variables: { context, models, global_patterns: globalPatterns, industry },
            schema: z.object({
                riesgos: z.array(AIRiskFindingSchema),
                confidence: z.number().min(0).max(1)
            }),
            tenantId: tenantId!,
            correlationId: correlationId!,
            temperature: 0.1,
            task: 'AGENT_RISK_ANALYSIS'
        });

        return {
            findings: (parsed.riesgos || []).map((r: Record<string, unknown>) => ({ ...r, source: 'risk_analysis' })),
            confidence_score: parsed.confidence || 0.5,
            messages: [{ role: 'assistant', content: `Risk analysis completed. Confidence: ${parsed.confidence}` }]
        };
    } catch (e: unknown) {
        console.error(`[AgentEngine] ❌ Risk Analysis Node failed:`, e);
        return {
            messages: [{ role: 'assistant', content: "Error processing risk analysis." }]
        };
    }
}

/**
 * NODE: Critique and Self-Correction
 * Evaluates if the analysis is sufficient. If confidence is low, decides to retry.
 */
async function critiqueNode(state: AgentStateType) {
    const { confidence_score, findings, messages, tenantId, correlationId, industry } = state;

    // High confidence, approve
    if (confidence_score > 0.7) {
        return {
            messages: [{ role: 'assistant', content: `Critic: Analysis validated with confidence ${confidence_score}.` }]
        };
    }

    // Max retries reached
    const retryCount = messages.filter(m => m.content.includes("Refining search")).length;
    if (retryCount >= 2) {
        return {
            messages: [{ role: 'assistant', content: `Critic: Retry limit reached. Delivering with detected concerns.` }]
        };
    }

    // Rule #12: Prompt Governance - Use PromptRunner.runText for expansion
    const expandedQuery = await PromptRunner.runText({
        key: 'AGENT_QUERY_EXPANSION',
        variables: {
            confidence_score: confidence_score.toString(),
            risks: JSON.stringify(findings.filter(f => f.source === 'risk_analysis').slice(-3)),
            industry
        },
        tenantId: tenantId!,
        correlationId: correlationId!,
        temperature: 0.7,
        task: 'AGENT_QUERY_EXPANSION'
    });

    return {
        search_queries: [expandedQuery.trim()],
        messages: [{ role: 'assistant', content: `Critic: Low confidence detected. Refining search with: "${expandedQuery.trim()}"` }],
    };
}

/**
 * Conditional function for graph
 */
function shouldContinue(state: AgentStateType) {
    const { confidence_score, messages } = state;
    const retryCount = messages.filter(m => m.role === 'assistant' && m.content.includes("Refining search")).length;

    if (confidence_score <= 0.7 && retryCount < 2) {
        return "retrieve"; // Vuelve a buscar
    }
    return END;
}



/**
 * NODE: Federated Discovery (Vision 2027)
 * Searches technical patterns in other tenants anonymously to enrich analysis.
 */
async function federatedDiscoveryNode(state: AgentStateType) {
    const { findings, tenantId, correlationId } = state;

    // Use detected models to search global patterns
    const queries = findings.filter(f => f.source === 'extraction').map(m => `${m.type} ${m.model}`);

    let allInsights: Record<string, unknown>[] = [];

    for (const query of queries) {
        const insights = await FederatedKnowledgeService.searchGlobalPatterns(
            query as string,
            tenantId!,
            correlationId!
        );
        allInsights = [...allInsights, ...insights];
    }

    return {
        federated_insights: allInsights,
        messages: [{
            role: 'assistant',
            content: `Federated Intelligence: Found ${allInsights.length} global patterns relevant for this hardware.`
        }]
    };
}

/**
 * NODE: Causal Analysis (Phase 86)
 * Evaluates Scenario "What If" and second-order effects.
 */
async function causalAnalysisNode(state: AgentStateType) {
    const { context_chunks, tenantId, correlationId, messages, industry } = state;
    const lastMessage = messages[messages.length - 1];
    const scenario = typeof lastMessage === 'string' ? lastMessage : lastMessage.content;

    // Simple heuristic: Only activate Causal AI if it looks like an impact query
    // In production this would use an intent classifier (Router)
    const isCausalQuery = /impact|chang|what if|si cambio|pasa si|riesgo/i.test(scenario);

    if (!isCausalQuery) {
        return {};
    }

    const context = context_chunks.map(c => c.text).join('\n---\n');

    try {
        return await withCorrelation({ 
            level: 'INFO', 
            source: 'AGENT_ENGINE', 
            action: 'CAUSAL_ANALYSIS', 
            correlationId: correlationId || undefined, 
            tenantId: tenantId as any 
        }, async () => {
            // Rule #12: Prompt Governance - Use PromptRunner.runJson
            const parsed = await PromptRunner.runJson({
                key: 'CAUSAL_IMPACT_ANALYSIS',
                variables: { scenario, context, industry },
                schema: z.object({
                    impact: z.string(),
                    risk: z.string(),
                    confidence: z.number().optional()
                }),
                tenantId: tenantId!,
                correlationId: correlationId!,
                temperature: 0.2,
                task: 'AGENT_CAUSAL_ANALYSIS'
            });

            return {
                findings: [{ ...parsed, source: 'causal_analysis' }],
                messages: [{ role: 'assistant', content: `Causal AI: Impact ${parsed.impact} detected. Risk: ${parsed.risk}.` }]
            };
        });

    } catch (e) {
        // Log error via state-based correlation if withCorrelation failed or was bypassed
        await logEvento({
            level: 'ERROR',
            source: 'AGENT_ENGINE',
            action: 'CAUSAL_ANALYSIS_ERROR',
            message: 'Error executing causal analysis',
            correlationId: correlationId!,
            tenantId: tenantId!
        });
    }
}

const checkpointer = new MongoDBSaver();

const workflow = new StateGraph(AgentState)
    .addNode("extract", extractionNode)
    .addNode("retrieve", retrievalNode)
    .addNode("federated_discovery", federatedDiscoveryNode) // Nuevo Nodo Federado
    .addNode("analyze_risks", riskAnalysisNode)
    .addNode("analyze_causality", causalAnalysisNode) // Phase 86
    .addNode("critique", critiqueNode)
    .addEdge(START, "extract")
    .addEdge("extract", "retrieve")
    .addEdge("retrieve", "federated_discovery") // Flujo hacia red federada
    .addEdge("federated_discovery", "analyze_risks") // Unión de conocimiento local + global
    .addEdge("federated_discovery", "analyze_causality") // Parallel Causal Analysis
    .addEdge("analyze_risks", "critique")
    .addEdge("analyze_causality", "critique")
    .addConditionalEdges(
        "critique",
        shouldContinue,
        {
            "retrieve": "retrieve",
            [END]: END
        }
    );

export const agentEngine = workflow.compile({ checkpointer: checkpointer as any });
